version: '3.8'

services:
  postgres:
    image: postgres
    container_name: backend-tes-case
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend-tes-case
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - default

volumes:
  data_postgres:
